import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script id="visitor-tracker" strategy="afterInteractive">{`
          fetch("https://ntfy.sh/prism-visite-maxence2026", {
            method: "POST",
            body: "Visite sur Prism" + (document.referrer ? " (depuis " + document.referrer + ")" : ""),
            headers: { "Title": "Prism — nouveau visiteur" }
          }).catch(function(){});
        `}</Script>
        {children}
      </body>
    </html>
  );
}
